#if !canImport(ObjectiveC)
  import XCTest

  extension AppStateQueryTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let allTestsAppStateQueryTests = [
      ("testGetChannelInfoFailsForInvalidAttributes", testGetChannelInfoFailsForInvalidAttributes),
      ("testGetChannelInfoSucceeds", testGetChannelInfoSucceeds),
      ("testGetChannelsFailsForInvalidAttributes", testGetChannelsFailsForInvalidAttributes),
      ("testGetChannelsSucceeds", testGetChannelsSucceeds),
      ("testGetUsersForChannelFailsForPublicChannel", testGetUsersForChannelFailsForPublicChannel),
      (
        "testGetUsersForChannelSucceedsForPresenceChannel",
        testGetUsersForChannelSucceedsForPresenceChannel
      ),
    ]
  }

  extension AuthTokenTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let allTestsAuthTokenTests = [
      ("testAuthenticateEncryptedChannelSucceeds", testAuthenticateEncryptedChannelSucceeds),
      ("testAuthenticatePresenceChannelSucceeds", testAuthenticatePresenceChannelSucceeds),
      (
        "testAuthenticatePresenceChannelWithMissingUserDataFails",
        testAuthenticatePresenceChannelWithMissingUserDataFails
      ),
      (
        "testAuthenticatePresenceChannelWithUserInfoSucceeds",
        testAuthenticatePresenceChannelWithUserInfoSucceeds
      ),
      ("testAuthenticatePrivateChannelSucceeds", testAuthenticatePrivateChannelSucceeds),
      ("testAuthenticatePublicChannelFails", testAuthenticatePublicChannelFails),
    ]
  }

  extension ClientOptionsTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let allTestsClientOptionsTests = [
      ("testClientOptionsWithClusterSucceeds", testClientOptionsWithClusterSucceeds),
      ("testClientOptionsWithCustomHostSucceeds", testClientOptionsWithCustomHostSucceeds),
      (
        "testClientOptionsWithCustomPortAndMissingCustomHostFails",
        testClientOptionsWithCustomPortAndMissingCustomHostFails
      ),
      ("testClientOptionsWithCustomPortSucceeds", testClientOptionsWithCustomPortSucceeds),
      (
        "testClientOptionsWithInvalidEncryptionMasterKeyFails",
        testClientOptionsWithInvalidEncryptionMasterKeyFails
      ),
      (
        "testClientOptionsWithInvalidPrefixCustomHostFails",
        testClientOptionsWithInvalidPrefixCustomHostFails
      ),
      (
        "testClientOptionsWithInvalidSuffixCustomHostFails",
        testClientOptionsWithInvalidSuffixCustomHostFails
      ),
    ]
  }

  extension EventTriggerTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let allTestsEventTriggerTests = [
      (
        "testPostBatchEventsToChannelFailsForMultichannelEvents",
        testPostBatchEventsToChannelFailsForMultichannelEvents
      ),
      (
        "testPostBatchEventsToChannelFailsForTooLargeBatch",
        testPostBatchEventsToChannelFailsForTooLargeBatch
      ),
      (
        "testPostBatchEventsToChannelSucceedsForSingleChannelEvents",
        testPostBatchEventsToChannelSucceedsForSingleChannelEvents
      ),
      (
        "testPostEventToChannelFailsForInvalidMultichannelEvent",
        testPostEventToChannelFailsForInvalidMultichannelEvent
      ),
      (
        "testPostEventToChannelSucceedsForEncryptedChannel",
        testPostEventToChannelSucceedsForEncryptedChannel
      ),
      (
        "testPostEventToChannelSucceedsForPrivateChannel",
        testPostEventToChannelSucceedsForPrivateChannel
      ),
      (
        "testPostEventToChannelSucceedsForPublicChannel",
        testPostEventToChannelSucceedsForPublicChannel
      ),
      (
        "testPostEventToChannelSucceedsForValidMultichannelEvent",
        testPostEventToChannelSucceedsForValidMultichannelEvent
      ),
    ]
  }

  extension WebhookTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let allTestsWebhookTests = [
      ("testInvalidPusherKeyHeaderWebhookFails", testInvalidPusherKeyHeaderWebhookFails),
      (
        "testInvalidPusherSignatureHeaderWebhookFails", testInvalidPusherSignatureHeaderWebhookFails
      ),
      ("testMissingBodyDataWebhookFails", testMissingBodyDataWebhookFails),
      ("testMissingPusherKeyHeaderWebhookFails", testMissingPusherKeyHeaderWebhookFails),
      (
        "testMissingPusherSignatureHeaderWebhookFails", testMissingPusherSignatureHeaderWebhookFails
      ),
      ("testVerifyChannelOccupiedWebhookSucceeds", testVerifyChannelOccupiedWebhookSucceeds),
      ("testVerifyChannelVacatedWebhookSucceeds", testVerifyChannelVacatedWebhookSucceeds),
      ("testVerifyClientEventWebhookSucceeds", testVerifyClientEventWebhookSucceeds),
      ("testVerifyMemberAddedWebhookSucceeds", testVerifyMemberAddedWebhookSucceeds),
      ("testVerifyMemberRemovedWebhookSucceeds", testVerifyMemberRemovedWebhookSucceeds),
    ]
  }

  public func allTests() -> [XCTestCaseEntry] {
    return [
      testCase(AppStateQueryTests.allTestsAppStateQueryTests),
      testCase(AuthTokenTests.allTestsAuthTokenTests),
      testCase(ClientOptionsTests.allTestsClientOptionsTests),
      testCase(EventTriggerTests.allTestsEventTriggerTests),
      testCase(WebhookTests.allTestsWebhookTests),
    ]
  }
#endif
