#if !canImport(ObjectiveC)
import XCTest

extension AppStateQueryTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__AppStateQueryTests = [
        ("testGetChannelInfoFailsForInvalidAttributes", testGetChannelInfoFailsForInvalidAttributes),
        ("testGetChannelInfoSucceeds", testGetChannelInfoSucceeds),
        ("testGetChannelsFailsForInvalidAttributes", testGetChannelsFailsForInvalidAttributes),
        ("testGetChannelsSucceeds", testGetChannelsSucceeds),
        ("testGetUsersForChannelFailsForPublicChannel", testGetUsersForChannelFailsForPublicChannel),
        ("testGetUsersForChannelSucceedsForPresenceChannel", testGetUsersForChannelSucceedsForPresenceChannel),
    ]
}

extension AuthTokenTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__AuthTokenTests = [
        ("testAuthenticateEncryptedChannelSucceeds", testAuthenticateEncryptedChannelSucceeds),
        ("testAuthenticatePresenceChannelSucceeds", testAuthenticatePresenceChannelSucceeds),
        ("testAuthenticatePresenceChannelWithMissingUserDataFails", testAuthenticatePresenceChannelWithMissingUserDataFails),
        ("testAuthenticatePresenceChannelWithUserInfoSucceeds", testAuthenticatePresenceChannelWithUserInfoSucceeds),
        ("testAuthenticatePrivateChannelSucceeds", testAuthenticatePrivateChannelSucceeds),
        ("testAuthenticatePublicChannelFails", testAuthenticatePublicChannelFails),
    ]
}

extension ClientOptionsTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__ClientOptionsTests = [
        ("testClientOptionsWithClusterSucceeds", testClientOptionsWithClusterSucceeds),
        ("testClientOptionsWithCustomHostSucceeds", testClientOptionsWithCustomHostSucceeds),
        ("testClientOptionsWithCustomPortAndMissingCustomHostFails", testClientOptionsWithCustomPortAndMissingCustomHostFails),
        ("testClientOptionsWithCustomPortSucceeds", testClientOptionsWithCustomPortSucceeds),
        ("testClientOptionsWithInvalidEncryptionMasterKeyFails", testClientOptionsWithInvalidEncryptionMasterKeyFails),
        ("testClientOptionsWithInvalidPrefixCustomHostFails", testClientOptionsWithInvalidPrefixCustomHostFails),
        ("testClientOptionsWithInvalidSuffixCustomHostFails", testClientOptionsWithInvalidSuffixCustomHostFails),
    ]
}

extension EventTriggerTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__EventTriggerTests = [
        ("testPostBatchEventsToChannelFailsForMultichannelEvents", testPostBatchEventsToChannelFailsForMultichannelEvents),
        ("testPostBatchEventsToChannelFailsForTooLargeBatch", testPostBatchEventsToChannelFailsForTooLargeBatch),
        ("testPostBatchEventsToChannelSucceedsForSingleChannelEvents", testPostBatchEventsToChannelSucceedsForSingleChannelEvents),
        ("testPostBatchEventsWithIdempotencyKeySucceeds", testPostBatchEventsWithIdempotencyKeySucceeds),
        ("testPostEventToChannelFailsForInvalidMultichannelEvent", testPostEventToChannelFailsForInvalidMultichannelEvent),
        ("testPostEventToChannelSucceedsForEncryptedChannel", testPostEventToChannelSucceedsForEncryptedChannel),
        ("testPostEventToChannelSucceedsForPrivateChannel", testPostEventToChannelSucceedsForPrivateChannel),
        ("testPostEventToChannelSucceedsForPublicChannel", testPostEventToChannelSucceedsForPublicChannel),
        ("testPostEventToChannelSucceedsForValidMultichannelEvent", testPostEventToChannelSucceedsForValidMultichannelEvent),
        ("testPostEventWithIdempotencyKeySucceeds", testPostEventWithIdempotencyKeySucceeds),
        ("testPostEventWithIdempotencyKeySucceedsForEncryptedChannel", testPostEventWithIdempotencyKeySucceedsForEncryptedChannel),
        ("testEventIdempotencyKeyIsEncodedInJSON", testEventIdempotencyKeyIsEncodedInJSON),
        ("testEventWithoutIdempotencyKeyEncodesNullKey", testEventWithoutIdempotencyKeyEncodesNullKey),
        ("testGenerateIdempotencyKeyReturnsUniqueValues", testGenerateIdempotencyKeyReturnsUniqueValues),
        ("testGenerateIdempotencyKeyReturnsValidUUID", testGenerateIdempotencyKeyReturnsValidUUID),
    ]
}

extension WebhookTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__WebhookTests = [
        ("testInvalidSockudoKeyHeaderWebhookFails", testInvalidSockudoKeyHeaderWebhookFails),
        ("testInvalidSockudoSignatureHeaderWebhookFails", testInvalidSockudoSignatureHeaderWebhookFails),
        ("testMissingBodyDataWebhookFails", testMissingBodyDataWebhookFails),
        ("testMissingSockudoKeyHeaderWebhookFails", testMissingSockudoKeyHeaderWebhookFails),
        ("testMissingSockudoSignatureHeaderWebhookFails", testMissingSockudoSignatureHeaderWebhookFails),
        ("testVerifyChannelOccupiedWebhookSucceeds", testVerifyChannelOccupiedWebhookSucceeds),
        ("testVerifyChannelVacatedWebhookSucceeds", testVerifyChannelVacatedWebhookSucceeds),
        ("testVerifyClientEventWebhookSucceeds", testVerifyClientEventWebhookSucceeds),
        ("testVerifyMemberAddedWebhookSucceeds", testVerifyMemberAddedWebhookSucceeds),
        ("testVerifyMemberRemovedWebhookSucceeds", testVerifyMemberRemovedWebhookSucceeds),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(AppStateQueryTests.__allTests__AppStateQueryTests),
        testCase(AuthTokenTests.__allTests__AuthTokenTests),
        testCase(ClientOptionsTests.__allTests__ClientOptionsTests),
        testCase(EventTriggerTests.__allTests__EventTriggerTests),
        testCase(WebhookTests.__allTests__WebhookTests),
    ]
}
#endif
